"use client";
import React, { useState } from "react";
import { FiChevronDown } from "react-icons/fi";

const Faqs = () => {
  const [faqItems, setFaqItems] = useState([
    {
      title: "What is FOLKS Car?",
      content: (
        <div className="flex flex-col gap-4 ">
          FOLKS Car represents a car rental service that is exploring the use of
          NFTs (Non-Fungible Tokens) to offer investment opportunities to
          potential investors. The business aims to allow individuals to invest
          in car rental businesses by purchasing NFTs, which may entitle them to
          a share of the profits generated by the car rental business.
          <div>
            Read more about the FOLKS Car vision on our{" "}
            <span className="underline" style={{ color: "#DEA337" }}>
              Blog
            </span>
          </div>
        </div>
      ),
    },
    {
      title: "What is the IRL utility associated with FOLKS Pass?",
      content:
        "The FOLKS Pass extends beyond the digital realm, offering real-world benefits. As a pass holder, you gain access to exclusive in-person events, meet-ups, and experiences related to the FOLKS Car Collection.",
    },
    {
      title: "What rights does a Membership’s Pass NFT owner have?",
      content: (
        <div className="flex flex-col gap-2">
          FOLKS Car NFT owners have several rights and benefits, including but
          not limited to:
          <li>
            Access to exclusive content, experiences, or services not available
            to non-holders.
          </li>
          <li>
            A share of the revenue generated by the car rental business,
            providing a passive income stream.
          </li>
          <li>
            Participation in governance and decision-making processes related to
            the business.
          </li>
          <li>
            Owning a unique and limited edition digital asset representing a
            stake in the business.
          </li>
          <li>
            Access to partner benefits and collaborations with other businesses
            or brands.
          </li>
        </div>
      ),
    },
    {
      title: "How many Membership Pass can I mint?",
      content: "There's no limit to how many Membership Passes you can mint!",
    },
    {
      title: "Which Network will FOLKS Car live on?",
      content: "FOLKS Car will be minted on Ethereum.",
    },
    {
      title: "How do I purchase Membership’s Pass NFT?",
      content: (
        <div>
          If the collection is available on the FOLKS Car site, you first need
          to connect a wallet that supports Ethereum (Metamask Wallet) to the
          website. In some cases, our collections and assets are also offered on
          popular NFT marketplaces which support Ethereum network. Once you
          choose necessary asset, its amount and press Buy, the necessary amount
          of ETH will be deducted from your wallet, and NFT will appear in your
          wallet.
        </div>
      ),
    },
    {
      title: "Can I use my FOLKS Car NFT to rent a car at any time?",
      content: (
        <div>
          Yes, you can use your NFT to rent a car at any time within the
          specified period of usability. Just follow the{" "}
          <span className="underline" style={{ color: "#DEA337" }}>
            instructions
          </span>{" "}
          provided when booking your rental.
        </div>
      ),
    },
    {
      title: "Can I transfer or gift my FOLKS Car NFT to someone else?",
      content:
        "Yes, in many cases, Membership’s Pass NFTs are transferable, allowing you to gift or sell them to other individuals.",
    },
    {
      title: "What if I don't use NFT within the specified period?",
      content:
        "If you have purchased a Membership’s Pass NFT but do not use it within the specified period, you will still retain ownership of the NFT. It will remain in your wallet, and you can choose to use it whenever you're ready. Keep in mind that owning a FOLKS Car NFT can come with other benefits beyond immediate use, such as potential profit-sharing opportunities.",
    },
    {
      title: "How can I keep track of my earnings as a FOLKS Car NFT holder?",
      content:
        "You can monitor your earnings and rewards as a FOLKS Car NFT holder through our platform, which will provide transparency into rental transactions, revenue sharing, and dividends.",
    },
    {
      title: "What happens if I lose my NFT?",
      content:
        "If you lose your NFT, please contact our support team for assistance. We will guide you through the process of recovering or replacing your NFT.",
    },
    {
      title: "How to join the FOLKS Car community?",
      content: (
        <div>
          Join our community on Discord at{" "}
          <span className="underline" style={{ color: "#DEA337" }}>
            Discord
          </span>{" "}
          and check out the #faq channels. Keep in touch on{" "}
          <span className="underline" style={{ color: "#DEA337" }}>
            Twitter
          </span>{" "}
          to stay informed about new content challenges and other ways to join
          the Home List.
        </div>
      ),
    },
    {
      title: "How do I contact customer support for inquiries or assistance?",
      content:
        "You can reach our customer support team through the contact information provided on our official website. We're here to help with any questions or issues you may have regarding your NFT or rentals.",
    },
  ]);

  const [expandedItems, setExpandedItems] = useState({});

  const handleToggle = (index) => {
    setExpandedItems((prevExpanded) => {
      return {
        ...prevExpanded,
        [index]: !prevExpanded[index],
      };
    });
  };

  return (
    <div className="h-full w-full py-10 bg-060606 items-center flex flex-col">
      <h1 className="font-bold text-[32px] eurostile leading-normal">FAQS</h1>
      <div className="mt-[50px]" />
      <br />
      <div className="bg-none flex flex-col">
        {faqItems.map((item, index) => (
          <div key={index} className="flex-col">
            <div className="flex items-center justify-between">
              <p className="font-700  text-[32px]">{item.title}</p>
              <FiChevronDown
                onClick={() => {
                  handleToggle(index);
                }}
                style={{ color: "#fff", fontSize: "30px", cursor: "pointer" }}
                className={`ml-2 transition-transform ${
                  expandedItems[index] ? "transform rotate-180" : ""
                }`}
              />
            </div>
            <div>
              {expandedItems[index] && (
                <div
                  className={`flex w-full mt-5 flex-wrap ${
                    window.innerWidth >= 1023 && window.innerWidth <= 1099
                      ? "max-w-[1000px]"
                      : "max-w-[1090px]"
                  }`}
                >
                  <p
                    className="font-medium leading-30px"
                    style={{ wordWrap: "break-word" }}
                  >
                    {item.content}
                  </p>
                </div>
              )}
            </div>
            <div>
              <br />
              <div
                className="w-[1090px] linew h-[1.9px] bg-white"
                // style={{ opacity: 0.7 }}
              ></div>
            </div>
          </div>
        ))}
        <div className="mb-[100px]" />
      </div>
    </div>
  );
};

export default Faqs;
